sources += gnome.compile_resources(
    'language-resources',
    files('language.gresource.xml'),
    c_name: 'language'
)

sources += files(
    'cc-language-chooser.c',
    'cc-language-chooser.h',
    'cc-util.c',
    'cc-util.h',
    'scis-welcome-widget.c',
    'scis-welcome-widget.h',
    'scis-language-page.c',
    'scis-language-page.h',
)
